//! `#[sixer::port]` splits a port trait into query and command views.

use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::parse::Parser;
use syn::parse_quote;
use syn::visit_mut::VisitMut;
use syn::{
    Attribute, Error, FnArg, GenericParam, Ident, ItemTrait, Lifetime, Meta, Pat, ReceiverKind,
    Result, ReturnType, Safety, Signature, Token, TraitItem, TraitItemFn, Type, TypeImplTrait,
    TypeParamBound, TypeReference,
};

enum Side {
    Query,
    Command,
}

pub fn expand(attr: TokenStream2, item: TokenStream2) -> Result<TokenStream2> {
    let async_send = async_send_arg(attr)?;

    let mut trait_item: ItemTrait = syn::parse2(item)?;
    if let Some(unsafety) = &trait_item.unsafety {
        return Err(Error::new_spanned(unsafety, "port traits are safe"));
    }
    trait_item.modifiers.require_empty()?;
    if !trait_item.generics.params.is_empty() || trait_item.generics.where_clause.is_some() {
        return Err(Error::new_spanned(
            &trait_item.generics,
            "#[sixer::port] does not support generic port traits yet",
        ));
    }

    let mut queries = Vec::new();
    let mut commands = Vec::new();
    let mut errors: Option<Error> = None;
    for item in &mut trait_item.items {
        match item {
            TraitItem::Fn(method) => {
                let was_async = method.sig.asyncness.is_some();
                match prepare(method, async_send) {
                    Ok(Side::Query) => queries.push((method.clone(), async_send && was_async)),
                    Ok(Side::Command) => commands.push((method.clone(), async_send && was_async)),
                    Err(err) => push_error(&mut errors, err),
                }
            }
            other => push_error(
                &mut errors,
                Error::new_spanned(other, "#[sixer::port] supports methods only"),
            ),
        }
    }
    if let Some(err) = errors {
        return Err(err);
    }

    let ident = &trait_item.ident;
    let query_ident = format_ident!("{ident}Query");
    let command_ident = format_ident!("{ident}Command");
    let query_doc = format!("Query view of `{ident}`, generated by `#[sixer::port]`.");
    let command_doc = format!(
        "Command view of `{ident}`, generated by `#[sixer::port]`. Includes the query methods."
    );
    let query_forwards = queries
        .iter()
        .map(|(method, precise)| forward(ident, method, *precise));
    let command_query_forwards = queries
        .iter()
        .map(|(method, precise)| forward(ident, method, *precise));
    let command_forwards = commands
        .iter()
        .map(|(method, precise)| forward(ident, method, *precise));

    Ok(quote! {
        #trait_item

        #[doc = #query_doc]
        #[derive(Copy, Clone)]
        pub(crate) struct #query_ident<'a, T: ?::core::marker::Sized>(&'a T);

        impl<'a, This: #ident + ?::core::marker::Sized> #query_ident<'a, This> {
            pub(crate) fn new(inner: &'a This) -> Self {
                Self(inner)
            }

            #(#query_forwards)*
        }

        #[doc = #command_doc]
        #[derive(Copy, Clone)]
        pub(crate) struct #command_ident<'a, T: ?::core::marker::Sized>(&'a T);

        impl<'a, This: #ident + ?::core::marker::Sized> #command_ident<'a, This> {
            pub(crate) fn new(inner: &'a This) -> Self {
                Self(inner)
            }

            #(#command_query_forwards)*
            #(#command_forwards)*
        }
    })
}

fn prepare(method: &mut TraitItemFn, async_send: bool) -> Result<Side> {
    let side = take_marker(method)?;
    method.modifiers.require_empty()?;
    check_signature(&method.sig)?;
    let _ = arg_idents(&method.sig)?;
    if async_send {
        desugar_async_send(method)?;
    }
    Ok(side)
}

fn async_send_arg(attr: TokenStream2) -> Result<bool> {
    let mut found = false;
    syn::meta::parser(|meta| {
        if !meta.path.is_ident("async_send") {
            return Err(meta.error("#[sixer::port] accepts async_send"));
        }
        if found {
            return Err(meta.error("#[sixer::port(async_send)] is written once"));
        }
        if meta.input.peek(Token![=]) || meta.input.peek(syn::token::Paren) {
            return Err(meta.error("#[sixer::port(async_send)] takes no value"));
        }
        found = true;
        Ok(())
    })
    .parse2(attr)?;
    Ok(found)
}

fn desugar_async_send(method: &mut TraitItemFn) -> Result<()> {
    if method.sig.asyncness.is_none() {
        return Ok(());
    }
    if let ReturnType::Type(_, ty) = &method.sig.output
        && matches!(ty.as_ref(), Type::ImplTrait(_))
    {
        return Err(Error::new_spanned(
            &method.sig.output,
            "#[sixer::port(async_send)] rewrites async fn; this return is already impl Trait",
        ));
    }

    method.sig.asyncness = None;
    let output = match &method.sig.output {
        ReturnType::Default => quote! { () },
        ReturnType::Type(_, ty) => quote! { #ty },
    };
    method.sig.output = parse_quote! {
        -> impl ::core::future::Future<Output = #output> + ::core::marker::Send
    };
    if let Some(body) = method.default.take() {
        // The `async fn` body is the body of the future it returns.
        method.default = Some(parse_quote!({ async move #body }));
    }
    Ok(())
}

fn take_marker(method: &mut TraitItemFn) -> Result<Side> {
    let mut found: Option<Side> = None;
    let mut kept = Vec::with_capacity(method.attrs.len());
    for attr in method.attrs.drain(..) {
        match marker_side(&attr)? {
            Some(side) => {
                if found.is_some() {
                    return Err(Error::new_spanned(
                        attr,
                        "mark a port method with only one of #[query] or #[command]",
                    ));
                }
                found = Some(side);
            }
            None => kept.push(attr),
        }
    }
    method.attrs = kept;
    found.ok_or_else(|| {
        Error::new_spanned(
            &method.sig.ident,
            "mark this method with #[query] or #[command]",
        )
    })
}

fn marker_side(attr: &Attribute) -> Result<Option<Side>> {
    let side = if is_named(attr, "query") {
        Some(Side::Query)
    } else if is_named(attr, "command") {
        Some(Side::Command)
    } else {
        return Ok(None);
    };
    match &attr.meta {
        Meta::Path(_) => Ok(side),
        _ => Err(Error::new_spanned(
            attr,
            "#[query] and #[command] take no arguments",
        )),
    }
}

fn is_named(attr: &Attribute, name: &str) -> bool {
    if attr.path().is_ident(name) {
        return true;
    }
    let mut segments = attr.path().segments.iter();
    segments
        .next()
        .is_some_and(|segment| segment.ident == "sixer")
        && segments.next().is_some_and(|segment| segment.ident == name)
        && segments.next().is_none()
}

fn check_signature(sig: &Signature) -> Result<()> {
    if let Some(constness) = &sig.constness {
        return Err(Error::new_spanned(
            constness,
            "port methods are ordinary functions",
        ));
    }
    if let Some(abi) = &sig.abi {
        return Err(Error::new_spanned(
            abi,
            "port methods are ordinary functions",
        ));
    }
    if let Some(variadic) = &sig.variadic {
        return Err(Error::new_spanned(
            variadic,
            "port methods are ordinary functions",
        ));
    }
    match &sig.safety {
        Safety::Default => {}
        other => {
            return Err(Error::new_spanned(
                other,
                "port methods are ordinary functions",
            ));
        }
    }

    let Some(receiver) = sig.receiver() else {
        return Err(Error::new_spanned(&sig.ident, "port methods take &self"));
    };
    if receiver.mutability.is_some() {
        return Err(Error::new_spanned(receiver, "port methods take &self"));
    }
    match &receiver.kind {
        ReceiverKind::Reference(_, _, None) => Ok(()),
        _ => Err(Error::new_spanned(receiver, "port methods take &self")),
    }
}

fn forward(trait_ident: &Ident, method: &TraitItemFn, precise_capture: bool) -> TokenStream2 {
    let attrs = &method.attrs;
    let mut sig = method.sig.clone();
    if precise_capture {
        capture_port_lifetime(&mut sig);
    }
    let name = &sig.ident;
    let args = arg_idents(&sig).expect("signature was checked");
    let generics = type_and_const_args(&sig);
    let call = if generics.is_empty() {
        quote! { <This as #trait_ident>::#name(self.0, #(#args),*) }
    } else {
        quote! { <This as #trait_ident>::#name::<#(#generics),*>(self.0, #(#args),*) }
    };
    let body = if sig.asyncness.is_some() {
        quote! { #call.await }
    } else {
        call
    };
    quote! {
        #(#attrs)*
        pub(crate) #sig {
            #body
        }
    }
}

/// The view method's future borrows the port (`'a`), which outlives the
/// temporary view. Rust 2024 would also capture `&self` of that view, so a
/// closure could not return `env.database().get(...)`.
///
/// `use<...>` names `'a`, the port type, and every generic parameter of the
/// method. An elided argument lifetime becomes `'portN`. An elided lifetime
/// in the return type is the receiver's, so it becomes `'a`.
fn capture_port_lifetime(sig: &mut Signature) {
    let mut used = lifetime_names(sig);
    let mut fresh = Vec::new();
    for input in &mut sig.inputs {
        let FnArg::Typed(arg) = input else {
            continue;
        };
        name_elided_lifetimes(&mut arg.ty, &mut used, &mut fresh);
    }
    for lifetime in &fresh {
        sig.generics.params.push(parse_quote!(#lifetime));
    }

    let bound = precise_captures(sig);
    let ReturnType::Type(_, ty) = &mut sig.output else {
        return;
    };
    let Type::ImplTrait(impl_trait) = ty.as_mut() else {
        return;
    };
    bind_output_to_port(impl_trait);
    impl_trait.bounds.push(bound);
}

fn lifetime_names(sig: &Signature) -> Vec<String> {
    sig.generics
        .params
        .iter()
        .filter_map(|param| match param {
            GenericParam::Lifetime(lifetime) => Some(lifetime.lifetime.ident.to_string()),
            _ => None,
        })
        .collect()
}

fn name_elided_lifetimes(ty: &mut Type, used: &mut Vec<String>, fresh: &mut Vec<Lifetime>) {
    let mut visitor = Elision {
        used,
        fresh,
        replacement: None,
        next: 0,
    };
    visitor.visit_type_mut(ty);
}

fn bind_output_to_port(impl_trait: &mut TypeImplTrait) {
    let mut used = Vec::new();
    let mut fresh = Vec::new();
    let mut visitor = Elision {
        used: &mut used,
        fresh: &mut fresh,
        replacement: Some(parse_quote!('a)),
        next: 0,
    };
    visitor.visit_type_impl_trait_mut(impl_trait);
}

fn precise_captures(sig: &Signature) -> TypeParamBound {
    let mut parts = Vec::new();
    parts.push(quote!('a));
    for param in &sig.generics.params {
        if let GenericParam::Lifetime(lifetime) = param {
            let lifetime = &lifetime.lifetime;
            parts.push(quote!(#lifetime));
        }
    }
    parts.push(quote!(This));
    for param in &sig.generics.params {
        if let GenericParam::Type(ty) = param {
            let ident = &ty.ident;
            parts.push(quote!(#ident));
        }
    }
    for param in &sig.generics.params {
        if let GenericParam::Const(con) = param {
            let ident = &con.ident;
            parts.push(quote!(#ident));
        }
    }
    parse_quote!(use<#(#parts),*>)
}

/// Gives each elided lifetime a name the `use<...>` list can mention.
struct Elision<'a> {
    used: &'a mut Vec<String>,
    fresh: &'a mut Vec<Lifetime>,
    replacement: Option<Lifetime>,
    next: u32,
}

impl Elision<'_> {
    fn replacement(&mut self) -> Lifetime {
        if let Some(lifetime) = &self.replacement {
            return lifetime.clone();
        }
        loop {
            let name = format!("port{}", self.next);
            self.next += 1;
            if self.used.iter().any(|used| used == &name) {
                continue;
            }
            self.used.push(name.clone());
            let lifetime = Lifetime::new(&format!("'{name}"), Span::call_site());
            self.fresh.push(lifetime.clone());
            return lifetime;
        }
    }
}

impl VisitMut for Elision<'_> {
    fn visit_lifetime_mut(&mut self, lifetime: &mut Lifetime) {
        if lifetime.ident == "_" {
            *lifetime = self.replacement();
        }
    }

    fn visit_type_reference_mut(&mut self, ty: &mut TypeReference) {
        if ty.lifetime.is_none() {
            ty.lifetime = Some(self.replacement());
        }
        syn::visit_mut::visit_type_reference_mut(self, ty);
    }
}

fn type_and_const_args(sig: &Signature) -> Vec<TokenStream2> {
    sig.generics
        .params
        .iter()
        .filter_map(|param| match param {
            GenericParam::Type(ty) => {
                let ident = &ty.ident;
                Some(quote!(#ident))
            }
            GenericParam::Const(con) => {
                let ident = &con.ident;
                Some(quote!(#ident))
            }
            GenericParam::Lifetime(_) => None,
        })
        .collect()
}

fn arg_idents(sig: &Signature) -> Result<Vec<Ident>> {
    let mut idents = Vec::new();
    for arg in &sig.inputs {
        match arg {
            FnArg::Receiver(_) => {}
            FnArg::Typed(pat_type) => {
                let Pat::Ident(pat) = &*pat_type.pat else {
                    return Err(Error::new_spanned(
                        &pat_type.pat,
                        "port arguments use a plain name",
                    ));
                };
                if pat.by_ref.is_some() || pat.subpat.is_some() {
                    return Err(Error::new_spanned(
                        &pat_type.pat,
                        "port arguments use a plain name",
                    ));
                }
                idents.push(pat.ident.clone());
            }
        }
    }
    Ok(idents)
}

fn push_error(slot: &mut Option<Error>, err: Error) {
    match slot {
        Some(existing) => existing.combine(err),
        None => *slot = Some(err),
    }
}

#[cfg(test)]
mod tests {
    use syn::Item;

    use super::*;

    struct Items(Vec<Item>);

    impl syn::parse::Parse for Items {
        fn parse(input: syn::parse::ParseStream<'_>) -> Result<Self> {
            let mut items = Vec::new();
            while !input.is_empty() {
                items.push(input.parse()?);
            }
            Ok(Self(items))
        }
    }

    fn view_methods(items: &[Item], name: &str) -> Vec<String> {
        let Some(Item::Impl(impl_item)) = items.iter().find(|item| match item {
            Item::Impl(impl_item) => {
                impl_item.trait_.is_none()
                    && matches!(
                        &*impl_item.self_ty,
                        syn::Type::Path(path)
                            if path.path.segments.last().is_some_and(|segment| segment.ident == name)
                    )
            }
            _ => false,
        }) else {
            panic!("missing impl {name}");
        };
        impl_item
            .items
            .iter()
            .map(|item| match item {
                syn::ImplItem::Fn(method) => method.sig.ident.to_string(),
                _ => panic!("{name} contains a non-method"),
            })
            .collect()
    }

    #[test]
    fn splits_marked_methods_into_views() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                pub trait Database: Send + Sync {
                    #[query]
                    fn get(&self, id: u32) -> u32;

                    /// save
                    #[command]
                    fn put(&self, id: u32, value: u32);
                }
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();

        assert_eq!(view_methods(&items, "DatabaseQuery"), ["new", "get"]);
        assert_eq!(
            view_methods(&items, "DatabaseCommand"),
            ["new", "get", "put"]
        );
        assert!(items.iter().any(|item| {
            let Item::Struct(view) = item else {
                return false;
            };
            view.ident == "DatabaseQuery"
                && matches!(
                    &view.vis,
                    syn::Visibility::Restricted(vis) if vis.path.is_ident("crate")
                )
        }));

        let Item::Trait(original) = items
            .iter()
            .find(|item| matches!(item, Item::Trait(trait_item) if trait_item.ident == "Database"))
            .unwrap()
        else {
            unreachable!();
        };
        assert!(original.items.iter().all(|item| {
            let TraitItem::Fn(method) = item else {
                return false;
            };
            method
                .attrs
                .iter()
                .all(|attr| !attr.path().is_ident("query") && !attr.path().is_ident("command"))
        }));
        let TraitItem::Fn(put) = &original.items[1] else {
            panic!("put");
        };
        assert!(put.attrs.iter().any(|attr| attr.path().is_ident("doc")));
    }

    #[test]
    fn unmarked_method_is_an_error() {
        let err = expand(
            TokenStream2::new(),
            quote! {
                trait Database {
                    fn get(&self) -> u32;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("#[query]"));
    }

    #[test]
    fn empty_port_emits_empty_views() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                pub trait Clock: Send + Sync {}
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();
        assert_eq!(view_methods(&items, "ClockQuery"), ["new"]);
        assert_eq!(view_methods(&items, "ClockCommand"), ["new"]);
    }

    fn trait_fn<'a>(items: &'a [Item], trait_name: &str, method: &str) -> &'a TraitItemFn {
        let Some(Item::Trait(trait_item)) = items
            .iter()
            .find(|item| matches!(item, Item::Trait(trait_item) if trait_item.ident == trait_name))
        else {
            panic!("missing trait {trait_name}");
        };
        trait_item
            .items
            .iter()
            .find_map(|item| match item {
                TraitItem::Fn(method_item) if method_item.sig.ident == method => Some(method_item),
                _ => None,
            })
            .unwrap_or_else(|| panic!("missing {trait_name}::{method}"))
    }

    fn view_fn<'a>(items: &'a [Item], view: &str, method: &str) -> &'a syn::ImplItemFn {
        let Some(Item::Impl(impl_item)) = items.iter().find(|item| match item {
            Item::Impl(impl_item) => {
                impl_item.trait_.is_none()
                    && matches!(
                        &*impl_item.self_ty,
                        syn::Type::Path(path)
                            if path.path.segments.last().is_some_and(|segment| segment.ident == view)
                    )
            }
            _ => false,
        }) else {
            panic!("missing impl {view}");
        };
        impl_item
            .items
            .iter()
            .find_map(|item| match item {
                syn::ImplItem::Fn(method_item) if method_item.sig.ident == method => {
                    Some(method_item)
                }
                _ => None,
            })
            .unwrap_or_else(|| panic!("missing {view}::{method}"))
    }

    fn renders_send_future(sig: &Signature, output: &str) {
        assert!(sig.asyncness.is_none());
        let text = quote!(#sig).to_string();
        assert!(text.contains(":: core :: future :: Future"), "{text}");
        assert!(text.contains(":: core :: marker :: Send"), "{text}");
        assert!(text.contains(output), "{text}");
    }

    #[test]
    fn async_send_rewrites_async_fns_and_leaves_sync_fns() {
        let output = expand(
            quote!(async_send),
            quote! {
                #[doc = "port"]
                pub trait Mailbox: Send + Sync {
                    #[query]
                    async fn get(&self, id: u32) -> Option<u32>;

                    #[command]
                    fn stamp(&self) -> u32;

                    #[command]
                    async fn ping(&self);

                    #[query]
                    fn names(&self) -> impl Iterator<Item = u32>;

                    /// keep
                    #[query]
                    async fn echo<T>(&self, value: T) -> T {
                        value
                    }

                    #[query]
                    async fn find(&self, name: &str) -> usize;

                    #[query]
                    async fn label(&self) -> &str;

                    #[command]
                    async fn nth<const N: usize>(&self) -> u32;
                }
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();

        let Item::Trait(mailbox) = items
            .iter()
            .find(|item| matches!(item, Item::Trait(trait_item) if trait_item.ident == "Mailbox"))
            .unwrap()
        else {
            unreachable!();
        };
        assert!(mailbox.attrs.iter().any(|attr| attr.path().is_ident("doc")));

        let get = trait_fn(&items, "Mailbox", "get");
        renders_send_future(&get.sig, "Option < u32 >");
        assert!(get.default.is_none());

        let stamp = trait_fn(&items, "Mailbox", "stamp");
        assert!(stamp.sig.asyncness.is_none());
        let stamp_output = &stamp.sig.output;
        let stamp_text = quote!(#stamp_output).to_string();
        assert!(stamp_text.contains("u32"), "{stamp_text}");
        assert!(!stamp_text.contains("Future"), "{stamp_text}");

        let ping = trait_fn(&items, "Mailbox", "ping");
        renders_send_future(&ping.sig, "()");

        let names = trait_fn(&items, "Mailbox", "names");
        let names_output = &names.sig.output;
        let names_text = quote!(#names_output).to_string();
        assert!(names_text.contains("Iterator"), "{names_text}");
        assert!(!names_text.contains("Future"), "{names_text}");

        let echo = trait_fn(&items, "Mailbox", "echo");
        renders_send_future(&echo.sig, "T");
        assert!(echo.attrs.iter().any(|attr| attr.path().is_ident("doc")));
        let body = echo.default.as_ref().expect("default body");
        let body_text = quote!(#body).to_string();
        assert!(body_text.contains("async move"), "{body_text}");
        assert!(body_text.contains("value"), "{body_text}");

        let view_get = view_fn(&items, "MailboxQuery", "get");
        renders_send_future(&view_get.sig, "Option < u32 >");
        let view_get_sig = &view_get.sig;
        let view_get_text = quote!(#view_get_sig).to_string();
        assert!(
            view_get_text.contains("use < 'a , This >"),
            "{view_get_text}"
        );

        let view_echo = view_fn(&items, "MailboxQuery", "echo");
        let view_echo_sig = &view_echo.sig;
        let view_echo_text = quote!(#view_echo_sig).to_string();
        assert!(
            view_echo_text.contains("use < 'a , This , T >"),
            "{view_echo_text}"
        );
        let view_echo_body = &view_echo.block;
        let view_echo_body = quote!(#view_echo_body).to_string();
        assert!(view_echo_body.contains(":: < T >"), "{view_echo_body}");

        let view_find = view_fn(&items, "MailboxQuery", "find");
        let view_find_sig = &view_find.sig;
        let view_find_text = quote!(#view_find_sig).to_string();
        assert!(view_find_text.contains("& 'port0 str"), "{view_find_text}");
        assert!(
            view_find_text.contains("use < 'a , 'port0 , This >"),
            "{view_find_text}"
        );

        let view_label = view_fn(&items, "MailboxQuery", "label");
        let view_label_sig = &view_label.sig;
        let view_label_text = quote!(#view_label_sig).to_string();
        assert!(
            view_label_text.contains("Output = & 'a str"),
            "{view_label_text}"
        );
        assert!(
            view_label_text.contains("use < 'a , This >"),
            "{view_label_text}"
        );

        let view_nth = view_fn(&items, "MailboxCommand", "nth");
        let view_nth_sig = &view_nth.sig;
        let view_nth_text = quote!(#view_nth_sig).to_string();
        assert!(
            view_nth_text.contains("use < 'a , This , N >"),
            "{view_nth_text}"
        );
        let view_nth_body = &view_nth.block;
        let view_nth_body = quote!(#view_nth_body).to_string();
        assert!(view_nth_body.contains(":: < N >"), "{view_nth_body}");
        let view_body = &view_get.block;
        let view_body_text = quote!(#view_body).to_string();
        assert!(!view_body_text.contains("await"), "{view_body_text}");

        let view_stamp = view_fn(&items, "MailboxCommand", "stamp");
        assert!(view_stamp.sig.asyncness.is_none());
        let view_stamp_output = &view_stamp.sig.output;
        let view_stamp_text = quote!(#view_stamp_output).to_string();
        assert!(!view_stamp_text.contains("Future"), "{view_stamp_text}");
    }

    #[test]
    fn bare_port_keeps_a_handwritten_future() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                trait Database: Send + Sync {
                    #[query]
                    fn get(&self) -> impl Future<Output = u32> + Send;
                }
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();
        let get = trait_fn(&items, "Database", "get");
        assert!(get.sig.asyncness.is_none());
        let sig = &get.sig;
        let text = quote!(#sig).to_string();
        assert!(
            text.contains("impl Future < Output = u32 > + Send"),
            "{text}"
        );
        assert!(!text.contains("core :: future"), "{text}");

        let view_get = view_fn(&items, "DatabaseQuery", "get");
        let view_sig = &view_get.sig;
        let view_text = quote!(#view_sig).to_string();
        assert!(!view_text.contains("use <"), "{view_text}");
    }

    #[test]
    fn async_fn_without_async_send_stays_async() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                trait Database: Send + Sync {
                    #[query]
                    async fn get(&self) -> u32;
                }
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();
        assert!(trait_fn(&items, "Database", "get").sig.asyncness.is_some());
        assert!(
            view_fn(&items, "DatabaseQuery", "get")
                .sig
                .asyncness
                .is_some()
        );
    }

    #[test]
    fn port_accepts_only_async_send() {
        let err = expand(
            quote!(send),
            quote! {
                trait Database {
                    #[query]
                    fn get(&self) -> u32;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("accepts async_send"));
    }

    #[test]
    fn async_send_is_written_once() {
        let err = expand(
            quote!(async_send, async_send),
            quote! {
                trait Database {
                    #[query]
                    fn get(&self) -> u32;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("written once"));
    }

    #[test]
    fn async_send_takes_no_value() {
        let err = expand(
            quote!(async_send = true),
            quote! {
                trait Database {
                    #[query]
                    fn get(&self) -> u32;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("takes no value"));
    }

    #[test]
    fn async_send_rejects_an_impl_trait_return() {
        let err = expand(
            quote!(async_send),
            quote! {
                trait Database {
                    #[query]
                    async fn get(&self) -> impl Iterator<Item = u32>;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("already impl Trait"));
    }
}
