//! `#[sixer::port]` splits a port trait into query and command views.

use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::{
    Attribute, Error, FnArg, Ident, ItemTrait, Meta, Pat, ReceiverKind, Result, Safety, Signature,
    TraitItem, TraitItemFn,
};

enum Side {
    Query,
    Command,
}

pub fn expand(attr: TokenStream2, item: TokenStream2) -> Result<TokenStream2> {
    if !attr.is_empty() {
        return Err(Error::new_spanned(
            attr,
            "#[sixer::port] takes no arguments",
        ));
    }

    let mut trait_item: ItemTrait = syn::parse2(item)?;
    if let Some(unsafety) = &trait_item.unsafety {
        return Err(Error::new_spanned(unsafety, "port traits are safe"));
    }
    trait_item.modifiers.require_empty()?;
    if !trait_item.generics.params.is_empty() || trait_item.generics.where_clause.is_some() {
        return Err(Error::new_spanned(
            &trait_item.generics,
            "#[sixer::port] does not support generic port traits yet",
        ));
    }

    let mut queries = Vec::new();
    let mut commands = Vec::new();
    let mut errors: Option<Error> = None;
    for item in &mut trait_item.items {
        match item {
            TraitItem::Fn(method) => match prepare(method) {
                Ok(Side::Query) => queries.push(method.clone()),
                Ok(Side::Command) => commands.push(method.clone()),
                Err(err) => push_error(&mut errors, err),
            },
            other => push_error(
                &mut errors,
                Error::new_spanned(other, "#[sixer::port] supports methods only"),
            ),
        }
    }
    if let Some(err) = errors {
        return Err(err);
    }

    let ident = &trait_item.ident;
    let query_ident = format_ident!("{ident}Query");
    let command_ident = format_ident!("{ident}Command");
    let query_doc = format!("Query view of `{ident}`, generated by `#[sixer::port]`.");
    let command_doc = format!(
        "Command view of `{ident}`, generated by `#[sixer::port]`. Includes the query methods."
    );
    let query_forwards = queries.iter().map(|method| forward(ident, method));
    let command_query_forwards = queries.iter().map(|method| forward(ident, method));
    let command_forwards = commands.iter().map(|method| forward(ident, method));

    Ok(quote! {
        #trait_item

        #[doc = #query_doc]
        #[derive(Copy, Clone)]
        pub(crate) struct #query_ident<'a, T: ?::core::marker::Sized>(&'a T);

        impl<'a, This: #ident + ?::core::marker::Sized> #query_ident<'a, This> {
            pub(crate) fn new(inner: &'a This) -> Self {
                Self(inner)
            }

            #(#query_forwards)*
        }

        #[doc = #command_doc]
        #[derive(Copy, Clone)]
        pub(crate) struct #command_ident<'a, T: ?::core::marker::Sized>(&'a T);

        impl<'a, This: #ident + ?::core::marker::Sized> #command_ident<'a, This> {
            pub(crate) fn new(inner: &'a This) -> Self {
                Self(inner)
            }

            #(#command_query_forwards)*
            #(#command_forwards)*
        }
    })
}

fn prepare(method: &mut TraitItemFn) -> Result<Side> {
    let side = take_marker(method)?;
    method.modifiers.require_empty()?;
    check_signature(&method.sig)?;
    let _ = arg_idents(&method.sig)?;
    Ok(side)
}

fn take_marker(method: &mut TraitItemFn) -> Result<Side> {
    let mut found: Option<Side> = None;
    let mut kept = Vec::with_capacity(method.attrs.len());
    for attr in method.attrs.drain(..) {
        match marker_side(&attr)? {
            Some(side) => {
                if found.is_some() {
                    return Err(Error::new_spanned(
                        attr,
                        "mark a port method with only one of #[query] or #[command]",
                    ));
                }
                found = Some(side);
            }
            None => kept.push(attr),
        }
    }
    method.attrs = kept;
    found.ok_or_else(|| {
        Error::new_spanned(
            &method.sig.ident,
            "mark this method with #[query] or #[command]",
        )
    })
}

fn marker_side(attr: &Attribute) -> Result<Option<Side>> {
    let side = if is_named(attr, "query") {
        Some(Side::Query)
    } else if is_named(attr, "command") {
        Some(Side::Command)
    } else {
        return Ok(None);
    };
    match &attr.meta {
        Meta::Path(_) => Ok(side),
        _ => Err(Error::new_spanned(
            attr,
            "#[query] and #[command] take no arguments",
        )),
    }
}

fn is_named(attr: &Attribute, name: &str) -> bool {
    if attr.path().is_ident(name) {
        return true;
    }
    let mut segments = attr.path().segments.iter();
    segments
        .next()
        .is_some_and(|segment| segment.ident == "sixer")
        && segments.next().is_some_and(|segment| segment.ident == name)
        && segments.next().is_none()
}

fn check_signature(sig: &Signature) -> Result<()> {
    if let Some(constness) = &sig.constness {
        return Err(Error::new_spanned(
            constness,
            "port methods are ordinary functions",
        ));
    }
    if let Some(abi) = &sig.abi {
        return Err(Error::new_spanned(
            abi,
            "port methods are ordinary functions",
        ));
    }
    if let Some(variadic) = &sig.variadic {
        return Err(Error::new_spanned(
            variadic,
            "port methods are ordinary functions",
        ));
    }
    match &sig.safety {
        Safety::Default => {}
        other => {
            return Err(Error::new_spanned(
                other,
                "port methods are ordinary functions",
            ));
        }
    }

    let Some(receiver) = sig.receiver() else {
        return Err(Error::new_spanned(&sig.ident, "port methods take &self"));
    };
    if receiver.mutability.is_some() {
        return Err(Error::new_spanned(receiver, "port methods take &self"));
    }
    match &receiver.kind {
        ReceiverKind::Reference(_, _, None) => Ok(()),
        _ => Err(Error::new_spanned(receiver, "port methods take &self")),
    }
}

fn forward(trait_ident: &Ident, method: &TraitItemFn) -> TokenStream2 {
    let attrs = &method.attrs;
    let sig = &method.sig;
    let name = &sig.ident;
    let args = arg_idents(sig).expect("signature was checked");
    let call = quote! { <This as #trait_ident>::#name(self.0, #(#args),*) };
    let body = if sig.asyncness.is_some() {
        quote! { #call.await }
    } else {
        call
    };
    quote! {
        #(#attrs)*
        pub(crate) #sig {
            #body
        }
    }
}

fn arg_idents(sig: &Signature) -> Result<Vec<Ident>> {
    let mut idents = Vec::new();
    for arg in &sig.inputs {
        match arg {
            FnArg::Receiver(_) => {}
            FnArg::Typed(pat_type) => {
                let Pat::Ident(pat) = &*pat_type.pat else {
                    return Err(Error::new_spanned(
                        &pat_type.pat,
                        "port arguments use a plain name",
                    ));
                };
                if pat.by_ref.is_some() || pat.subpat.is_some() {
                    return Err(Error::new_spanned(
                        &pat_type.pat,
                        "port arguments use a plain name",
                    ));
                }
                idents.push(pat.ident.clone());
            }
        }
    }
    Ok(idents)
}

fn push_error(slot: &mut Option<Error>, err: Error) {
    match slot {
        Some(existing) => existing.combine(err),
        None => *slot = Some(err),
    }
}

#[cfg(test)]
mod tests {
    use syn::Item;

    use super::*;

    struct Items(Vec<Item>);

    impl syn::parse::Parse for Items {
        fn parse(input: syn::parse::ParseStream<'_>) -> Result<Self> {
            let mut items = Vec::new();
            while !input.is_empty() {
                items.push(input.parse()?);
            }
            Ok(Self(items))
        }
    }

    fn view_methods(items: &[Item], name: &str) -> Vec<String> {
        let Some(Item::Impl(impl_item)) = items.iter().find(|item| match item {
            Item::Impl(impl_item) => {
                impl_item.trait_.is_none()
                    && matches!(
                        &*impl_item.self_ty,
                        syn::Type::Path(path)
                            if path.path.segments.last().is_some_and(|segment| segment.ident == name)
                    )
            }
            _ => false,
        }) else {
            panic!("missing impl {name}");
        };
        impl_item
            .items
            .iter()
            .map(|item| match item {
                syn::ImplItem::Fn(method) => method.sig.ident.to_string(),
                _ => panic!("{name} contains a non-method"),
            })
            .collect()
    }

    #[test]
    fn splits_marked_methods_into_views() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                pub trait Database: Send + Sync {
                    #[query]
                    fn get(&self, id: u32) -> u32;

                    /// save
                    #[command]
                    fn put(&self, id: u32, value: u32);
                }
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();

        assert_eq!(view_methods(&items, "DatabaseQuery"), ["new", "get"]);
        assert_eq!(
            view_methods(&items, "DatabaseCommand"),
            ["new", "get", "put"]
        );
        assert!(items.iter().any(|item| {
            let Item::Struct(view) = item else {
                return false;
            };
            view.ident == "DatabaseQuery"
                && matches!(
                    &view.vis,
                    syn::Visibility::Restricted(vis) if vis.path.is_ident("crate")
                )
        }));

        let Item::Trait(original) = items
            .iter()
            .find(|item| matches!(item, Item::Trait(trait_item) if trait_item.ident == "Database"))
            .unwrap()
        else {
            unreachable!();
        };
        assert!(original.items.iter().all(|item| {
            let TraitItem::Fn(method) = item else {
                return false;
            };
            method
                .attrs
                .iter()
                .all(|attr| !attr.path().is_ident("query") && !attr.path().is_ident("command"))
        }));
        let TraitItem::Fn(put) = &original.items[1] else {
            panic!("put");
        };
        assert!(put.attrs.iter().any(|attr| attr.path().is_ident("doc")));
    }

    #[test]
    fn unmarked_method_is_an_error() {
        let err = expand(
            TokenStream2::new(),
            quote! {
                trait Database {
                    fn get(&self) -> u32;
                }
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("#[query]"));
    }

    #[test]
    fn empty_port_emits_empty_views() {
        let output = expand(
            TokenStream2::new(),
            quote! {
                pub trait Clock: Send + Sync {}
            },
        )
        .unwrap();
        let Items(items) = syn::parse2(output).unwrap();
        assert_eq!(view_methods(&items, "ClockQuery"), ["new"]);
        assert_eq!(view_methods(&items, "ClockCommand"), ["new"]);
    }
}
